name: CI

on:
  push:
    branches: [main]

  pull_request:
    types: [opened, synchronize]
    branches: [main]

  workflow_dispatch:

jobs:
  ci:
    name: Node.js
    uses: 4mbl/actions/.github/workflows/ci-node-pnpm.yaml@57b1db6e95fa6cedea8d3270f3f4142fba10c63b # ci-node-pnpm/v26.9.0
    with:
      disable-steps: '[]'
